### ISSUE TITLE
Downloading the exact phone name

### ISSUE THREAD

**Issue by braciawrite** [aafanasev/fonoapi-client#1]
I am using a database download via php and I limit it to only download the first value. I need to download after the exact name of the model. For example, if the database is Apple iPhone 6s then the name iPhone 6s will not find me. For example, if I have a Samsung Galaxy Note 8 it shows me parameters from Samsung Galaxy Note 8.0, and this specification is not satisfactory for me

**Comment by aafanasev** [comment]
This repository is about a java client. You should ask your question in https://github.com/shakee93/fonoapi/issues
